# Generated by Django 4.2.10 on 2025-09-21 22:31

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default=core.models.random_avatar, max_length=2),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('permission', models.CharField(blank=True, default='', max_length=50)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('store_count', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息库',
            },
        ),
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1', models.CharField(blank=True, default='', max_length=100)),
                ('level2', models.CharField(blank=True, default='', max_length=100)),
                ('level3', models.CharField(blank=True, default='', max_length=100)),
                ('word', models.CharField(max_length=200)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '敏感词',
                'verbose_name_plural': '敏感词库',
                'indexes': [models.Index(fields=['word'], name='core_sensit_word_6649d6_idx'), models.Index(fields=['level1', 'level2', 'level3'], name='core_sensit_level1_59adec_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeywordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1', models.CharField(blank=True, default='', max_length=100)),
                ('level2', models.CharField(blank=True, default='', max_length=100)),
                ('level3', models.CharField(blank=True, default='', max_length=100)),
                ('word', models.CharField(max_length=200)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词库',
                'indexes': [models.Index(fields=['word'], name='core_keywor_word_4a81a5_idx'), models.Index(fields=['level1', 'level2', 'level3'], name='core_keywor_level1_1a1d1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForbiddenWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1', models.CharField(blank=True, default='', max_length=100)),
                ('level2', models.CharField(blank=True, default='', max_length=100)),
                ('level3', models.CharField(blank=True, default='', max_length=100)),
                ('word', models.CharField(max_length=200)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '违禁词',
                'verbose_name_plural': '违禁词库',
                'indexes': [models.Index(fields=['word'], name='core_forbid_word_c1ccb0_idx'), models.Index(fields=['level1', 'level2', 'level3'], name='core_forbid_level1_70d5c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='BrandWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('word', models.CharField(max_length=200)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '品牌词',
                'verbose_name_plural': '品牌词库',
                'indexes': [models.Index(fields=['word'], name='core_brandw_word_50ff9b_idx'), models.Index(fields=['category'], name='core_brandw_categor_6cfc1b_idx')],
            },
        ),
    ]
