# Generated by Django 4.2.10 on 2025-09-22 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_avatar_userinfo_sensitiveword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '词分类',
                'verbose_name_plural': '词分类',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, unique=True)),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='core.category')),
            ],
            options={
                'verbose_name': '词条',
                'verbose_name_plural': '词条库',
            },
        ),
        migrations.CreateModel(
            name='WordLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, default='')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.word')),
            ],
            options={
                'verbose_name': '词命中记录',
                'verbose_name_plural': '词命中记录',
                'indexes': [models.Index(fields=['matched_at'], name='core_wordlo_matched_a11dc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='WordAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.word')),
            ],
            options={
                'verbose_name': '词别名',
                'verbose_name_plural': '词别名',
                'indexes': [models.Index(fields=['alias'], name='core_wordal_alias_681159_idx')],
                'unique_together': {('word', 'alias')},
            },
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['word'], name='core_word_word_dc2883_idx'),
        ),
    ]
