# Generated by Django 4.2.10 on 2025-09-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_word_wordlog_wordalias_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandWord',
        ),
        migrations.DeleteModel(
            name='KeywordEntry',
        ),
        migrations.DeleteModel(
            name='SensitiveWord',
        ),
    ]
