# Generated by Django 4.2.10 on 2025-09-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_brandword_delete_keywordentry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForbiddenWord',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
        migrations.AlterModelOptions(
            name='wordalias',
            options={'verbose_name': 'Word Alias', 'verbose_name_plural': 'Word Aliases'},
        ),
        migrations.AlterModelOptions(
            name='wordlog',
            options={'verbose_name': 'Word Hit Log', 'verbose_name_plural': 'Word Hit Logs'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='word',
            name='severity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'low'), (2, 'medium'), (3, 'high')], default=1),
        ),
    ]
