# Generated by Django 5.2.6 on 2025-09-23 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_forbiddenword_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'User Info', 'verbose_name_plural': 'User Info'},
        ),
        migrations.CreateModel(
            name='StoreKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_person', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Key',
                'verbose_name_plural': 'Store Keys',
                'indexes': [models.Index(fields=['user'], name='core_storek_user_id_989909_idx'), models.Index(fields=['store_code'], name='core_storek_store_c_4b124b_idx')],
                'unique_together': {('user', 'store_code')},
            },
        ),
    ]
