# Generated by Django 4.2.10 on 2025-09-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userinfo_options_storekey'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points_consumed', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(blank=True, default='')),
                ('store_code', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Usage Log',
                'verbose_name_plural': 'Usage Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_usagel_created_36a7f7_idx'), models.Index(fields=['store_code'], name='core_usagel_store_c_aa99d9_idx')],
            },
        ),
    ]
