# Generated by Django 4.2.10 on 2025-09-26 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_usagelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagelog',
            options={'verbose_name': 'Usage Log', 'verbose_name_plural': 'Usage Logs'},
        ),
        migrations.AddField(
            model_name='usagelog',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failure', 'failure')], default='success', max_length=10),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='points_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PointsBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.CharField(max_length=100)),
                ('points', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Points Balance',
                'verbose_name_plural': 'Points Balances',
                'indexes': [models.Index(fields=['user'], name='core_points_user_id_ea25e9_idx'), models.Index(fields=['store_code'], name='core_points_store_c_e4d89b_idx')],
                'unique_together': {('user', 'store_code')},
            },
        ),
    ]
