# Generated by Django 4.2.10 on 2025-09-26 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_usagelog_options_usagelog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '成功'), ('failed', '失败')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='status',
            field=models.CharField(choices=[('success', '成功'), ('failure', '失败')], default='success', max_length=10),
        ),
    ]
