# Generated by Django 4.2.10 on 2025-09-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopcode', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trial',
                'verbose_name_plural': 'Trials',
                'db_table': 'trials',
                'indexes': [models.Index(fields=['shopcode'], name='trials_shopcod_fd6f51_idx')],
            },
        ),
    ]
