# Generated by Django 4.2.10 on 2025-10-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64)),
                ('title', models.TextField(blank=True, default='')),
                ('image_url', models.TextField(blank=True, default='')),
                ('time_start', models.DateField(blank=True, null=True)),
                ('time_end', models.DateField(blank=True, null=True)),
                ('gross_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_card_buyer_cnt', models.IntegerField(blank=True, null=True)),
                ('product_card_ctr', models.FloatField(blank=True, null=True)),
                ('product_card_cvr', models.FloatField(blank=True, null=True)),
                ('product_card_gmv', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_card_listing_impression_cnt', models.IntegerField(blank=True, null=True)),
                ('product_card_pv', models.IntegerField(blank=True, null=True)),
                ('product_card_unit_sold_cnt', models.IntegerField(blank=True, null=True)),
                ('product_card_uv', models.IntegerField(blank=True, null=True)),
                ('unit_sold_cnt', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sales Info',
                'verbose_name_plural': 'Sales Info',
                'indexes': [models.Index(fields=['product_id'], name='core_salesi_product_72b7dd_idx'), models.Index(fields=['time_start'], name='core_salesi_time_st_c778db_idx'), models.Index(fields=['time_end'], name='core_salesi_time_en_f5b594_idx')],
                'unique_together': {('product_id', 'time_start', 'time_end')},
            },
        ),
    ]
